Working station
AmaliaGM/GettingStarted pull request #1
Opened 2022-05-25 03:37 UTC by AmaliaGM

2022-05-25 13:30 UTC, sja-thedude requested changes
## Required Changes ♻️

Hi @AmaliaGM, This is @sja-thedude your code reviewer.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![768070f3-bc9a-4aba-b8bc-25793e00ea1e_text](https://user-images.githubusercontent.com/70269507/159483175-2f61461d-b352-4cb4-98f8-b173e05ab5ff.gif)

## Highlights
✔️ Professional Readme
✔️ Correct git-flow
✔️ Good job so far

## Required 
- [ ] Kindly setup your linters correctly. Delete the existing .github/workflows and Make sure to add all the files except readme from [here](https://github.com/microverseinc/linters-config/tree/master/html-css). Also, make sure all the linters pass and have a green checkmark.
- [ ] Kindly update your readme file with your contact details and delete the unnecessary heading which is not required.
- [ ] Kindly add a descriptive Pull request title as shown in the image marked 1. Replace `Working station` with `Hello Microverse Project`.
- [ ] Kindly add a pull request description as shown in the image marked 2. Make sure to add the description by clicking the 3 dots on the right side.

![2022-05-25 (2)_LI](https://user-images.githubusercontent.com/70269507/170272029-69038a40-18ee-470b-9f2f-5232e7817f57.jpg)

- [ ] _Check the comments under the review._

## Optional suggestions
- [ ] Kindly make sure from next time name your branch more meaningful.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-25 13:30 UTC, sja-thedude commented on .gitignore
> +test.md
- [ ] Kindly make sure to also add node_modules to the .gitignore file as per the requirement.

2022-05-25 13:30 UTC, sja-thedude commented on .github/workflows/-github-workflows-linters.yml.url
> +URL=https://github.com/microverseinc/linters-config/blob/master/html-css/.github/workflows/linters.yml
- [ ] Kindly delete this file and setup linters as asked in the summary.

2022-05-25 19:51 UTC, AmaliaGM reviewed
hi.. I did the changes but as soon as I deleted the headding it went red and no workflow is running (I think). Thanks for your advices.

2022-05-25 20:45 UTC, sja-thedude commented
@AmaliaGM you have to reopen this PR , currently it’s closed!

2022-05-25 20:47 UTC, AmaliaGM commented
I dont know how.. tried to request a review of the changes

2022-05-25 20:57 UTC, AmaliaGM commented
@sja-thedude done! Sorry about that

2022-05-26 00:06 UTC, AmaliaGM commented
@sja-thedude Hi. It came to my knowing  that you can not rename a branch while in a pull request (it closes by defect). So I won't need able to do it without closing the request.

2022-05-26 01:25 UTC, sja-thedude commented
> @sja-thedude Hi. It came to my knowing  that you can not rename a branch while in a pull request (it closes by defect). So I won't be able to do it without closing the request. 

@AmaliaGM I have kept the renaming of branch as optional! You have to rename the pull request title and description!

2022-05-26 01:28 UTC, AmaliaGM commented
Great. Thanks for your response.

2022-05-26 16:12 UTC, zieeco requested changes
Hi @AmaliaGM 


Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the changes, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Nice design. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._


<img src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>


## Optional suggestions
- As the other reviewer missed this part, please consider them a a mandatory requirement. Please update your readme by adding all the missing tags from the [microverse readme template](https://github.com/microverseinc/readme-template) to make your reamde more professional.

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-26 16:12 UTC, zieeco commented on README.md
**[REQUIRED CHANGES]**

- As required by the previous reviewer, please kindly update your readme and delete the unnecessary heading.
![above](https://user-images.githubusercontent.com/59397159/170528397-27d1fc42-a934-45e5-ab6c-42e4d5d914aa.png)

2022-05-26 16:57 UTC, AmaliaGM commented
@zieeco thanks for your feedback will make the changes.

2022-05-26 17:04 UTC, Munsa1 approved these changes
Hi @AmaliaGM  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Descriptive readme
- Passing linters
- Correct gitflow
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-26 17:55 UTC, AmaliaGM commented
@Munsa1 Thanks for your review! Happy codding!

2022-05-26 17:55 UTC, merged

2022-10-11 08:18 UTC, AmaliaGM commented
How?

Obtener Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
From: Syeda Juveria Afreen ***@***.***>
Sent: Wednesday, May 25, 2022 5:45:26 PM
To: AmaliaGM/GettingStarted ***@***.***>
Cc: AmaliaGM ***@***.***>; Mention ***@***.***>
Subject: Re: [AmaliaGM/GettingStarted] Working station (PR #1)


@AmaliaGM<https://github.com/AmaliaGM> you have to reopen this PR , currently it’s closed!

—
Reply to this email directly, view it on GitHub<https://github.com/AmaliaGM/GettingStarted/pull/1#issuecomment-1137831301>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AYVYTXMITQUM6ODW4CWBEA3VL2GONANCNFSM5W3UTAFA>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-10-11 09:06 UTC, AmaliaGM commented
Van I please get some help with the linter set up? As for the workflow,if I erase that file,does not work at all.

Obtener Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
From: Syeda Juveria Afreen ***@***.***>
Sent: Wednesday, May 25, 2022 10:30:21 AM
To: AmaliaGM/GettingStarted ***@***.***>
Cc: AmaliaGM ***@***.***>; Mention ***@***.***>
Subject: Re: [AmaliaGM/GettingStarted] Working station (PR #1)


@sja-thedude requested changes on this pull request.

Required Changes ♻️

Hi @AmaliaGM<https://github.com/AmaliaGM>, This is @sja-thedude<https://github.com/sja-thedude> your code reviewer.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

[768070f3-bc9a-4aba-b8bc-25793e00ea1e_text]<https://user-images.githubusercontent.com/70269507/159483175-2f61461d-b352-4cb4-98f8-b173e05ab5ff.gif>

Highlights

✔️ Professional Readme
✔️ Correct git-flow
✔️ Good job so far

Required

  *    Kindly setup your linters correctly. Delete the existing .github/workflows and Make sure to add all the files except readme from here<https://github.com/microverseinc/linters-config/tree/master/html-css>. Also, make sure all the linters pass and have a green checkmark.
  *    Kindly update your readme file with your contact details and delete the unnecessary heading which is not required.
  *    Kindly add a descriptive Pull request title as shown in the image marked 1. Replace Working station with Hello Microverse Project.
  *    Kindly add a pull request description as shown in the image marked 2. Make sure to add the description by clicking the 3 dots on the right side.

[2022-05-25 (2)_LI]<https://user-images.githubusercontent.com/70269507/170272029-69038a40-18ee-470b-9f2f-5232e7817f57.jpg>

  *    Check the comments under the review.

Optional suggestions

  *    Kindly make sure from next time name your branch more meaningful.

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me ***@***.***<https://github.com/sja-thedude>] in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

________________________________

As described in the Code reviews limits policy<https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this form<https://airtable.com/shrQAqnBwek5a0O0s>.

________________________________

In .gitignore<https://github.com/AmaliaGM/GettingStarted/pull/1#discussion_r881630718>:

> @@ -0,0 +1 @@

+test.md



  *    Kindly make sure to also add node_modules to the .gitignore file as per the requirement.

________________________________

In .github/workflows/-github-workflows-linters.yml.url<https://github.com/AmaliaGM/GettingStarted/pull/1#discussion_r881638955>:

> +[InternetShortcut]

+URL=https://github.com/microverseinc/linters-config/blob/master/html-css/.github/workflows/linters.yml



  *    Kindly delete this file and setup linters as asked in the summary.

—
Reply to this email directly, view it on GitHub<https://github.com/AmaliaGM/GettingStarted/pull/1#pullrequestreview-984779459>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AYVYTXNYM4VICEPDP4TG6QDVLYTO3ANCNFSM5W3UTAFA>.
You are receiving this because you were mentioned.Message ID: ***@***.***>